#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "is-password-protected"
version = "0.1.0"
authors = ["Thorsten Hans <thans@akamai.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "is-password-protected"

[component.is-password-protected]
source = "target/wasm32-wasip1/release/is_password_protected.wasm"
files = ["assets/*"]

allowed_outbound_hosts = []

[component.is-password-protected.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
